---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: 'È possibile aggiornare sul posto una macchina virtuale dell"utilità Deploy esistente tramite l"interfaccia della riga di comando.' 
---
= Aggiorna un'istanza di ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile aggiornare sul posto una macchina virtuale dell'utilità Deploy esistente tramite l'interfaccia della riga di comando.



== Prima di iniziare

Assicurarsi che Deploy non venga utilizzato per eseguire altre attività durante l'aggiornamento. È necessario consultare le note di rilascio correnti per informazioni e restrizioni sull'aggiornamento dell'utilità Deploy.


NOTE: Se è installata una versione precedente dell'utilità di amministrazione ONTAP Select Deploy, è necessario eseguire l'aggiornamento alla versione corrente. Il nodo ONTAP Select e il componente ONTAP Select Deploy vengono aggiornati in modo indipendente. Vedere link:concept_adm_upgrading_nodes.html["Aggiornare i nodi ONTAP Select"^] per ulteriori dettagli.



== Scarica il pacchetto di aggiornamento

Per avviare il processo di aggiornamento, è necessario scaricare il file di aggiornamento della macchina virtuale Deploy appropriato dal NetApp Support Site. Il pacchetto di aggiornamento è formattato come un singolo file compresso.

.Passi
. Accedi al link:https://mysupport.netapp.com/site/["Sito di supporto NetApp"^] utilizzando un browser web e scegli *Downloads* dal menu Downloads.
. Scorri verso il basso e seleziona *ONTAP Select Deploy Upgrade*.
. Seleziona la release desiderata del pacchetto di aggiornamento.
. Rivedi il Contratto di licenza con l'utente finale (EULA) e seleziona *Accetta e continua*.
. Seleziona e scarica il pacchetto appropriato, rispondendo a tutte le richieste secondo le necessità del tuo ambiente.




== Carica il pacchetto sulla macchina virtuale Deploy

Dopo aver acquisito il pacchetto di upgrade, è necessario caricare il file sulla macchina virtuale Deploy.

.Prima di iniziare
È necessario che il file di aggiornamento sia disponibile sulla workstation locale. È inoltre necessario disporre della password per l'account utente amministratore.

.Informazioni su queste attività
Questa attività descrive un metodo per caricare il file sulla macchina virtuale Deploy. Potrebbero esserci altre opzioni più adatte al tuo ambiente.

.Passi
. In una shell dei comandi sulla workstation locale, usa l'utilità scp per caricare il file immagine sulla macchina virtuale Deploy.
+
Esempio

+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.Risultato
Il file di aggiornamento è archiviato nella directory home dell'utente amministratore.



== Applica il pacchetto di aggiornamento

Dopo che il file di aggiornamento è stato caricato sulla macchina virtuale Deploy, è possibile applicare l'aggiornamento.

.Prima di iniziare
È necessario conoscere la directory in cui è stato posizionato il file di aggiornamento nella macchina virtuale dell'utility Deploy. Assicurarsi inoltre che Deploy non venga utilizzato per eseguire altre attività durante l'aggiornamento.

.Passi
. Sign in all'utility Deploy CLI tramite SSH con l'account amministratore.
. Eseguire l'aggiornamento utilizzando il percorso della directory e il nome del file appropriati:
+
`deploy upgrade -package-path FILEPATH`

+
Esempio

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.Dopo aver finito
Prima del completamento della procedura di aggiornamento, ti verrà chiesto di creare un backup della configurazione della macchina virtuale Deploy. Inoltre, dovresti cancellare la cache del browser così da poter visualizzare le pagine Deploy appena create.
